-- T_社員テーブルのカラム情報を取得
SELECT
    COLUMN_NAME,
    DATA_TYPE,
    CHARACTER_MAXIMUM_LENGTH,
    IS_NULLABLE,
    COLUMN_DEFAULT
FROM
    INFORMATION_SCHEMA.COLUMNS
WHERE
    TABLE_NAME = 'T_社員'
    AND TABLE_CATALOG = 'VcareDB'
ORDER BY
    ORDINAL_POSITION;